### ISSUE TITLE
Closing brace unexpectedly moves cursor to line start

### ISSUE THREAD

**Issue by kwshi** [ALSchwalm/elvish-mode#11]
When I define a function, it is my habit to type the closing brace together with the opening brace, and then insert the contents inside:

```
fn fn-name {}
```

After typing the last `}`, my cursor immediately teleports to the start of the line.  This is undesirable behavior.

**Comment by zzamboni** [comment]
I have noticed the same behavior.

**Comment by ALSchwalm** [comment]
It looks like this is caused by the modification of `electric-indent-chars` here https://github.com/ALSchwalm/elvish-mode/blob/9cf31b453ac79b011b84e83ca11c964c4e647649/elvish-mode.el#L256

I'm not sure why I put this in. It seems like the indenting works as expected without it, so I will probably just remove that.

**Comment by zzamboni** [comment]
Thanks! Works now.
